### ISSUE TITLE
`build_docker_image` default timeout not respected

### ISSUE THREAD

**Issue by hughgardiner** [stelligent/minimal-pipeline-gem#17]
With some of our gem heavy ruby images, we are seeing timeouts in 5 minutes rather than 10 minutes as would be expected by the default timeout option of 600 seconds
```ruby
 def build_docker_image(image_id, build_context: '.',
                           dockerfile: 'Dockerfile',
                           build_args: {},
                           timeout: 600)
# ...
::Docker.options[:read_timeout] = timeout
```
we did not have this issue when the gem we were using took a more brute force approach at setting the timeout like so:
```ruby
::Docker.options = { timeout: 36_000,
                             read_timeout: 36_000,
                             write_timeout: 36_000 }
```
I haven't been able to prove which `timeout` option actually gets respected by Swipely's `docker-api` gem, but it seems like `timeout` is the option respected over the `read_timeout` option

**Comment by jesseadams** [comment]
Thanks for the report @hughgardiner. I can try to do some digging and try to get to the bottom of this. How badly is this effecting your builds?

**Comment by hughgardiner** [comment]
not bad, we can set the other timeout options in our rake tasks prior to calling `build_docker_image` or in our wrapper gem as well. merely wanted to bring to your all's attention

**Comment by hughgardiner** [comment]
if it's helpful, we're seeing the timeout source from `excon` 
```Excon::Error::Timeout: read timeout reached```
```IO::EAGAINWaitReadable: Resource temporarily unavailable - read would block
/var/lib/jenkins/.rvm/gems/ruby-2.5.1/gems/excon-0.64.0/lib/excon/socket.rb:64:in `readline'```

from reading the docker-api/excon documentation, the approach in place for setting `:read_timeout` via ``::Docker.options` sounds like it should be working, so i'm at a loss for why it's not

**Comment by jesseadams** [comment]
Tried to reproduce this locally. So far no luck. Will try a newer 2.5.x.

```bash
$ time ruby test.rb
Building docker image
Step 1/2 : FROM alpine

 ---> 055936d39205
Step 2/2 : RUN sleep 900

 ---> Running in 472b6640453e
Traceback (most recent call last):
	6: from test.rb:5:in `<main>'
	5: from /Users/jesse/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/minimal_pipeline-0.3.1/lib/minimal_pipeline/docker.rb:87:in `build_docker_image'
	4: from /Users/jesse/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/docker-api-1.34.2/lib/docker/image.rb:293:in `build_from_dir'
	3: from /Users/jesse/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/docker-api-1.34.2/lib/docker/image.rb:274:in `build_from_tar'
	2: from /Users/jesse/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/docker-api-1.34.2/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
	1: from /Users/jesse/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/docker-api-1.34.2/lib/docker/connection.rb:37:in `request'
/Users/jesse/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/docker-api-1.34.2/lib/docker/connection.rb:52:in `rescue in request': read timeout reached (Docker::Error::TimeoutError)

real	10m15.850s
user	0m12.090s
sys	0m1.201s

$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin16]
```

**Comment by jesseadams** [comment]
@hughgardiner Please try version 0.3.2, and pass in your timeout value to `build_docker_image`. Please report in if it resolves your issues.

Thanks!

**Comment by hughgardiner** [comment]
@jesseadams I've updated one of our services to use `0.3.2` and as of now has passed each time :) thank you!

**Comment by jesseadams** [comment]
Thanks for reporting back in!
